name: test-builder
on: repository_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run pwd 1
        run: pwd

      - uses: actions/checkout@v1
        with:
          name: boson-project/func
      - name: Run pwd 2
        run: pwd

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Run
        run: "echo '${{ toJson(github.event.client_payload) }}' | ./builder-image-test"
